# Generated by Django 3.0.2 on 2020-03-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spec', '0002_auto_20200301_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityAdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City', models.CharField(default='', max_length=100)),
                ('Meters', models.IntegerField(default='', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='specramadd',
            name='Computer',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='specramadd',
            name='Ram',
            field=models.CharField(default='', max_length=100),
        ),
    ]
