# Generated by Django 3.0.2 on 2020-03-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spec', '0003_auto_20200302_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameHost', models.CharField(default='', max_length=50)),
                ('NameMail', models.CharField(default='', max_length=50)),
                ('PassMail', models.CharField(default='', max_length=50)),
                ('NameToSend', models.CharField(default='', max_length=50)),
                ('NamePort', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
