# Generated by Django 3.0.2 on 2020-03-30 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Spec', '0004_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Options',
            new_name='OptionsM',
        ),
    ]
