# Generated by Django 3.0.2 on 2020-03-30 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Spec', '0005_auto_20200330_1854'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OptionsM',
            new_name='Options',
        ),
    ]
